### ISSUE TITLE
Github Topics

### ISSUE THREAD

**Issue by igneus** [Nocturnale-Romanum/nocturnale-romanum#1]
[Topics](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics) help make the repository discoverable for people interested in this kind of things (and thus potential users and/or contributors).

I would suggest adding at least these:

- [gabc](https://github.com/topics/gabc)
- [gregorio](https://github.com/topics/gregorio)
- [gregorian-chant](https://github.com/topics/gregorian-chant)
- [divine-office](https://github.com/topics/divine-office)

**Comment by xmarteo** [comment]
Done, thanks for the suggestion.
