### ISSUE TITLE
typos/possible revisions (mostly in the introduction)

### ISSUE THREAD

**Issue by MRoth1910** [Nocturnale-Romanum/nocturnale-romanum#18]
- according th –> according to
- according to "X rubrics" sounds unidiomatic to my ears, and I'd personally write "according to the X" rubrics"
- as is the case also –> as is also the case
- commas aren't strictly needed around "in part"

Would you consider using English rules for the English version? The extra padding provided by the language packages for French-style punctuation does look a little off with English.

In the body: I do appreciate the judicious use of some rhythmic markings. For the indications of the psalm tone, using lower case consistently is interesting; capitals for the final (particularly in transposed chants like IV A) is helpful to me, but making this more explicit would be of benefit, perhaps in the introduction. Ditto syllabification. I stick to the Liber Usualis when possible, but Ben Bloomfield used the new pattern, more or less, (so I change things like st or ct to s-t or c-t, and I occasionally pour over the books to figure out the rules in individual cases); doing that doesn't bother me too terribly much, it's just not going to match what people already might use (for Christmas and Holy Week or for the dead in particular).

I'll try to read through the whole draft later — I don't want to complain too much about something that I don't know how fix, because I too have rivers and lakes of white in the psalms when I use columns, but that's the biggest thing that jumps out.

Anyway, having a draft of such a work in the first "useful" volume is tremendous. It's excellent news.

**Comment by xmarteo** [comment]
is "according to either the 1960 rubrics or DA rubrics" correct, or should it be "according to either the 1960 rubrics or THE DA rubrics" ?

**Comment by xmarteo** [comment]
Lowercase psalm tones: I have never understood the logic behind the use of upper vs lowercase in the Liber usualis. Recent books use only lowercase, I have followed them without asking myself questions.

**Comment by MRoth1910** [comment]
Capitals are used for the final (hence 8G but 8c, based of course on a correspondance of letter names to solfège names). As I said, I'm able to adapt, but it will look different, so it's worth a note.

Definitely no need to repeat rubrics. I don't think that you need to repeat the article.

No worries with the process of revision of syllabification.

**Comment by xmarteo** [comment]
Do you mean that capitals are used when the final of the psalm tone is the same as the final of the mode? It looks like it it indeed the case. I must say I don't find it useful at all.

**Comment by xmarteo** [comment]
Noted. I think there are a whole abundance of such details that will puzzle "ordinary trads", like the absence of ictus while other rhythmic signs are present, neographies for liquescences and the oriscus-based neumes, the fact that the book just assumes you know what you should include or omit (e.g. gives two different feasts on may 1st with very little rubrics to explain why), or even the concept of a book that does not cover all parts of a few hours (like the LU does), but a few parts of many hours.
Going into all this in the foreword would risk bringing me over KDP's 550 page limit, from which I am already very dangerously close...

**Comment by xmarteo** [comment]
I will close this for the time being, the English mistakes and typography being fixed in https://github.com/Nocturnale-Romanum/psalterium-festivum/commit/8d98c2fd80dc21f69e5066de25c8ef5752674209

Please do open a sepatate issues for hyphenation errors if you find the courage to list them, or some of them. I will try to automate their detection some time in the summer, but now is not the time.
