### ISSUE TITLE
GABC directory full (too many names/files)

### ISSUE THREAD

**Issue by leduc006** [Nocturnale-Romanum/nocturnale-romanum#3]
It seems we'll have to reclassify groups of gabc files into subdirectories or something, perhaps under a top-level gabc directory.  When I visit the gabc directory, it tells me it stops at 1000 files and 453 or so could not be uploaded.

Not a crisis at the moment, but something to fix at some point.

**Comment by xmarteo** [comment]
The files cannot be displayed but they have been uploaded. If you checkout the repository using git clone, or, if you do not have git, if you download the zip of the repository (repository root page > Code > Download ZIP), you will see that they are there.

Having all the GABC in a single folder is helpful for a possible future evolution of the system where we would separate responds and verses (and doxologies), and assemble the "final" GABC files at compile time.

**Comment by xmarteo** [comment]
(Do reopen this issue if the GABC directory structure starts being a problem with the maintainability or compilation of the NR. However, it is to be noted that GABC should be edited mostly via the website, and not directly on GitHub. Specifically, there is no mechanism for changes made on GitHub to be backported into the website.)
