### ISSUE TITLE
Mis-hyphenation of text

### ISSUE THREAD

**Issue by Suinesra** [Nocturnale-Romanum/nocturnale-romanum#42]
Liber Responsorialis de Tempore, pg. 535
Resp. Misit Dominus

=> The doxology ends with: _et Spir-ri-tu-i Sanc-to._

Latin liturgical hyphenation should be: _et Spir-ri-tu-i San-cto._

**Comment by xmarteo** [comment]
The more recent Solesmes books (e.g. Liber Hymnarius, see p. 604sq) have Sanc-to. This is what has been followed throughout the book - it is instances of San-cto that should be reported. To be honest I don't care, but other contributors have been insistent that we use the newer hyphenation.
