### ISSUE TITLE
Textual transcription error

### ISSUE THREAD

**Issue by Suinesra** [Nocturnale-Romanum/nocturnale-romanum#44]
Sandhofe "Nocturnale Romanum", pg 379*
Responsory 3: "O beatum virum"

The beginning of the repetition of the response is given in the final staff as "Qui- a.", but it ought to be "Qui nec".

**Comment by xmarteo** [comment]
Thanks - by coincidence, I saw it and fixed it yesterday: https://nocturnale.marteo.fr/chant/1111N1R3/ - I will keep reviewing the RR/ for St. Martin this week.
