### ISSUE TITLE
Singability?

### ISSUE THREAD

**Issue by Suinesra** [Nocturnale-Romanum/nocturnale-romanum#46]
_Nocturnale Romanum_, Hartker, 2002, p. 384*
Responsory 7: "O beatum virum"

The intervals in the neums over the text "Omniumque coe-" may correctly reflect the semiological signs in the original manuscripts (I'm not competent to assess that), but are almost un-singable.

Solely from a _melodic_ perspective, may I suggest the following change:
[O beatum virum.pdf](https://github.com/user-attachments/files/17710113/O.beatum.virum.pdf)

**Comment by xmarteo** [comment]
I agree. I think this version is musicologically correct and singable: 
![image](https://github.com/user-attachments/assets/64f7f4dc-6d8c-4cbd-a38e-5266d5a30397)
I leave this open until I get around to revising this particular R/

**Comment by xmarteo** [comment]
Fixed in https://nocturnale.marteo.fr/proposal/1111N3R1/marteo/
